# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-28 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description1',
            field=models.TextField(default='some string'),
        ),
        migrations.AddField(
            model_name='product',
            name='description2',
            field=models.TextField(default='some string'),
        ),
        migrations.AddField(
            model_name='product',
            name='excerpt',
            field=models.TextField(default='some string', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='some string'),
        ),
        migrations.AlterField(
            model_name='product',
            name='grind_size',
            field=models.CharField(choices=[('Extra Coarse', 'Extra Coarse'), ('Coarse', 'Coarse'), ('Medium Coarse', 'Medium Coarse'), ('Medium', 'Medium'), ('Medium Fine', 'Medium Fine'), ('Fine', 'Fine'), ('Very Fine', 'Very Fine')], default='Fine', max_length=20),
        ),
    ]
